version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_jwt
    restart: always
    environment:
      POSTGRES_DB: laravel_jwt
      POSTGRES_USER: laravel_root
      POSTGRES_PASSWORD: H3@rtDB@#00
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
